N: 4
F: 1
m: 3
IPList:
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
- 127.0.0.1
PID: 0
SID: 1
Snum: 2
PortList:
- 9233
- 9234
- 9235
- 9236
- 9237
- 9238
- 9239
- 9240
- 9241
- 9242
- 9243
- 9244
PrepareTime: 50
Statistic: ./statistics
WaitTime: 120
Txnum: 1000
Crate: 0.1
TestEpochs: 5